version: "3.1"

language: "en"

pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "CountVectorsFeaturizer"
- name: "DIETClassifier"

policies:
- name: "MemoizationPolicy"
- name: "RulePolicy"
- name: "TEDPolicy"
assistant_id: 20250111-173824-isomorphic-squib
